#include "Functions.h"

void Init() {
	
	//ACTIVATING CLOCK FOR THE REQUIRED PORTS A,B AND F
	SYSCTL_RCGCGPIO_R = 0x23;
	while (!(SYSCTL_PRGPIO_R & 0x23));

	//UNLOCKING PORTS
	GPIO_PORTA_LOCK_R = 0X4C4F434B;
	GPIO_PORTB_LOCK_R = 0X4C4F434B; 
	GPIO_PORTF_LOCK_R = 0X4C4F434B;
	GPIO_PORTA_CR_R = 0xFF;
	GPIO_PORTB_CR_R = 0xFF;
	GPIO_PORTF_CR_R = 0x1F;
	
	//AMSEL
	GPIO_PORTA_AMSEL_R = 0;
	GPIO_PORTB_AMSEL_R = 0;
	GPIO_PORTF_AMSEL_R = 0;

	//AFSEL
	GPIO_PORTA_AFSEL_R = 0x3;
	GPIO_PORTB_AFSEL_R = 0;
	GPIO_PORTF_AFSEL_R = 0;
	
	//PCTL
	GPIO_PORTA_PCTL_R = 0x11;
	GPIO_PORTB_PCTL_R = 0;
	GPIO_PORTF_PCTL_R = 0;

	//DEN
	GPIO_PORTA_DEN_R = 0xFF;
	GPIO_PORTB_DEN_R = 0xFF;
	GPIO_PORTF_DEN_R = 0x1F;

	//DIR
	GPIO_PORTA_DIR_R = 0xFC;
	GPIO_PORTB_DIR_R = 0xFF;
	GPIO_PORTF_DIR_R = 0xE;
}
